%% Import data from spreadsheet
% Script for importing data from the following spreadsheet:
%
%    Workbook: /Users/alikaynar/Desktop/UpgrdPostDoc/GEM/GEM_R_Second_Project/DEG_RES_2.xlsx
%    Worksheet: DESeq_Table_dds_high_low
%
% Auto-generated by MATLAB on 08-Feb-2024 13:49:09

%% Set up the Import Options and import the data
opts = spreadsheetImportOptions("NumVariables", 7);

% Specify sheet and range
opts.Sheet = "DESeq_Table_dds_NT_low";
opts.DataRange = "A2:G15985";

% Specify column names and types
opts.VariableNames = ["baseMean", "log2FoldChange", "lfcSE", "stat", "pvalue", "padj", "rownames"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "string"];

% Specify variable properties
opts = setvaropts(opts, "rownames", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "rownames", "EmptyFieldRule", "auto");

% Import the data
DESeq_Table_dds_NT_low = readtable("/Users/alikaynar/Desktop/UpgrdPostDoc/GEM/GEM_R_Second_Project/DEG_RES_2.xlsx", opts, "UseExcel", false);


%% Clear temporary variables
clear opts